INSERT INTO USUARIO (EMAIL,SENHA) VALUES ('teste@gmail.com','exemplo123');
INSERT INTO USUARIO (EMAIL,SENHA) VALUES ('eu@gmail.com','eu123');
-- USUARIO TESTE PARA TELA DE LOGIN

INSERT INTO CLIENTE (NOME,EMAIL,TELEFONE,ULTIMA_CONSULTA) VALUES ('ana','ana@gmail.com','111111111','20240520');
INSERT INTO CLIENTE (NOME, EMAIL,TELEFONE,ULTIMA_CONSULTA) VALUES ('beatriz','beatriz@gmail.com','222222222','20240520');
-- CLIENTE TESTE PARA TELA DE LOGIN